export default {
  primaryBlack: 'Poppins-Black',
  primaryBold: 'Poppins-Bold',
  primaryExtraBold: 'Poppins-ExtraBold',
  primaryMedium: 'Poppins-Medium',
  primary: 'Poppins-Regular',
  primarySemiBold: 'Poppins-SemiBold',

  arabicBlack: 'Tajawal-Black',
  arabicBold: 'Tajawal-Bold',
  arabicExtraBold: 'Tajawal-ExtraBold',
  arabicExtraLight: 'Tajawal-ExtraLight',
  arabicLight: 'Tajawal-Light',
  arabicMedium: 'Tajawal-Medium',
  arabicRegular: 'Tajawal-Regular',

  // primaryItalic: 'Poppins-Italic',
  // NafeesNaskh: 'NafeesNaskh',
  // PlayfairSemiBold: 'PlayfairDisplay-SemiBold',  
  // SourceSerifProBold: 'SourceSerifPro-Bold',
  // SourceSerifProSemiBold: 'SourceSerifPro-SemiBold',
  // SourceSerifProRegular: 'SourceSerifPro-Regular',
  // SourceSerifProLight: 'SourceSerifPro-Light',
  // SourceSerifProExtraLight: 'SourceSerifPro-ExtraLight',
};