export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const UPDATE_CURRENT_SCREEN = 'UPDATE_CURRENT_SCREEN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const UPDATE_DOWNLOADS = 'UPDATE_DOWNLOADS';
export const SET_USER_INFO = 'SET_USER_INFO';
export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';
export const UPDATE_NOTIFICATION_BADGE = 'UPDATE_NOTIFICATION_BADGE';
export const UPDATE_MESSAGE_BADGE = 'UPDATE_MESSAGE_BADGE';
export const UPDATE_FCM_TOKEN = 'UPDATE_FCM_TOKEN';
export const SET_DRAWER_MENU = 'SET_DRAWER_MENU';

export const SET_ERROR = 'SET_ERROR';

export const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
export const REGISTER_API_SUCCESS = 'REGISTER_API_SUCCESS';
export const DELETE_USER_API_SUCCESS = 'DELETE_USER_API_SUCCESS';
export const FORGET_PASSWORD_API_SUCCESS = 'FORGET_PASSWORD_API_SUCCESS';
export const SEND_OPT_API_SUCCESS = 'SEND_OPT_API_SUCCESS';
export const RESET_PASSWORD_API_SUCCESS = 'RESET_PASSWORD_API_SUCCESS';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const SUBMIT_OTP_API_SUCCESS = 'SUBMIT_OTP_API_SUCCESS';
export const RESEND_OTP_API_SUCCESS = 'RESEND_OTP_API_SUCCESS';
export const GET_PROFILE_API_SUCCESS = 'GET_PROFILE_API_SUCCESS';
export const REPORT_USER_API_SUCCESS = 'REPORT_USER_API_SUCCESS';
export const BLOCK_USER_API_SUCCESS = 'BLOCK_USER_API_SUCCESS';
export const UNBLOCK_USER_API_SUCCESS = 'UNBLOCK_USER_API_SUCCESS';
export const BLOCKED_USERS_LIST_API_SUCCESS = 'BLOCKED_USERS_LIST_API_SUCCESS';

export const EDIT_PROFILE_API_SUCCESS = 'EDIT_PROFILE_API_SUCCESS';
export const UPDATE_PROFILE_PIC_API_SUCCESS = 'UPDATE_PROFILE_PIC_API_SUCCESS';
export const UPDATE_PROFILE_PIC_API_ERROR = 'UPDATE_PROFILE_PIC_API_ERROR';
// export const GET_USER_PROFILE_API_SUCCESS = 'GET_USER_PROFILE_API_SUCCESS';
export const GET_OUR_STAFF_API_SUCCESS = 'GET_OUR_STAFF_API_SUCCESS';
export const GET_OUR_SPEAKER_API_SUCCESS = 'GET_OUR_SPEAKER_API_SUCCESS';

export const GET_POSTS_API_SUCCESS = 'GET_POSTS_API_SUCCESS';
export const GET_CDS_API_SUCCESS = 'GET_CDS_API_SUCCESS';
export const CLEAR_POST_LIST_SUCCESS = 'CLEAR_POST_LIST_SUCCESS';
export const GET_EVENTS_API_SUCCESS = 'GET_EVENTS_API_SUCCESS';
export const GET_UPCOMING_EVENTS_API_SUCCESS = 'GET_UPCOMING_EVENTS_API_SUCCESS';
export const GET_REQUESTED_PRAYER_API_SUCCESS = 'GET_REQUESTED_PRAYER_API_SUCCESS';
export const GET_NOTIFICATIONS_API_SUCCESS = 'GET_NOTIFICATIONS_API_SUCCESS';
export const GET_ANNOUNCEMENT_API_SUCCESS = 'GET_ANNOUNCEMENT_API_SUCCESS';
export const GET_BOOKS_API_SUCCESS = 'GET_BOOKS_API_SUCCESS';

export const GET_SERMONS_DETAIL_API_SUCCESS = 'GET_SERMONS_DETAIL_API_SUCCESS';
export const GET_POST_DETAIL_API_SUCCESS = 'GET_POST_DETAIL_API_SUCCESS';
export const GET_ANNOUNCEMENT_DETAIL_API_SUCCESS = 'GET_ANNOUNCEMENT_DETAIL_API_SUCCESS';
export const GET_EVENT_DETAIL_API_SUCCESS = 'GET_EVENT_DETAIL_API_SUCCESS';
export const GET_UPCOMING_EVENT_DETAIL_API_SUCCESS = 'GET_UPCOMING_EVENT_DETAIL_API_SUCCESS';
export const GET_OUR_STAFF_DETAIL_API_SUCCESS = 'GET_OUR_STAFF_DETAIL_API_SUCCESS';
export const GET_OUR_SPEAKER_DETAIL_API_SUCCESS = 'GET_OUR_SPEAKER_DETAIL_API_SUCCESS';
export const GET_BOOKS_DETAIL_API_SUCCESS = 'GET_BOOKS_DETAIL_API_SUCCESS';

export const CONTACT_API_SUCCESS = 'CONTACT_API_SUCCESS';
export const CONTACT_API_ERROR = 'CONTACT_API_ERROR';
export const REQUEST_PRAYER_API_SUCCESS = 'REQUEST_PRAYER_API_SUCCESS';
export const ABOUT_API_SUCCESS = 'ABOUT_API_SUCCESS';
export const HOME_BANNER_API_SUCCESS = 'HOME_BANNER_API_SUCCESS';

export const GET_GROUPS_API_SUCCESS = 'GET_GROUPS_API_SUCCESS';
export const GET_MESSAGES_API_SUCCESS = 'GET_MESSAGES_API_SUCCESS';
export const SEND_MESSAGES_API_SUCCESS = 'SEND_MESSAGES_API_SUCCESS';
export const SEND_MESSAGES_API_FAILURE = 'SEND_MESSAGES_API_FAILURE';
export const SEND_GROUP_REQUEST_API_SUCCESS = 'SEND_GROUP_REQUEST_API_SUCCESS';
export const DELETE_MESSAGES_API_SUCCESS = 'DELETE_MESSAGES_API_SUCCESS';
export const REPORT_MESSAGE_API_SUCCESS = 'REPORT_MESSAGE_API_SUCCESS';

export const GET_ASK_A_QUESTION = 'GET_ASK_A_QUESTION';
export const SEND_ASK_A_QUESTION = 'SEND_ASK_A_QUESTION';
export const GET_POST_BY_CATEGORY_ID_SUCCESS = 'GET_POST_BY_CATEGORY_ID_SUCCESS';
export const GET_POST_WO_TYPE_BY_CATEGORY_ID_SUCCESS = 'GET_POST_WO_TYPE_BY_CATEGORY_ID_SUCCESS';

export const ADD_TO_FAVOURITE_LIST_SUCCESS = 'ADD_TO_FAVOURITE_LIST_SUCCESS';
export const GET_FAVOURITE_LIST_SUCCESS = 'GET_FAVOURITE_LIST_SUCCESS';
export const GET_FAVOURITE_IDS_SUCCESS = 'GET_FAVOURITE_IDS_SUCCESS';
export const GET_FEATURED_LIST_SUCCESS = 'GET_FEATURED_LIST_SUCCESS';

export const ADD_POST_TO_HISTORY_SUCCESS = 'ADD_POST_TO_HISTORY_SUCCESS';
export const GET_HISTORY_LIST_SUCCESS = 'GET_HISTORY_LIST_SUCCESS';
export const GET_DAILIES_LIST_SUCCESS = 'GET_DAILIES_LIST_SUCCESS';
export const GET_SEARCH_POST_API_SUCCESS = 'GET_SEARCH_POST_API_SUCCESS';
export const GET_HOME_NEWS_LIST_SUCCESS = 'GET_HOME_NEWS_LIST_SUCCESS';

export const GET_HOME_BIBLICAL_DATA_SUCCESS = 'GET_HOME_BIBLICAL_DATA_SUCCESS';
export const GET_HOME_SPIRITUAL_DATA_SUCCESS = 'GET_HOME_AUDIO_DATA_SUCCESS';
export const GET_HOME_AUDIO_DATA_SUCCESS = 'GET_HOME_AUDIO_DATA_SUCCESS';
export const GET_HOME_AUDIO_NO_DATA_SUCCESS = 'GET_HOME_AUDIO_NO_DATA_SUCCESS';